export const environment = {
    production: true,
    apiUrl: 'http://app.autosite.com.ar:8099/backdemo/'
};export const BodyOKM = {
    tabla_automotor: 'UND',
    estado: 'SASG',
    ultimos: '100',
    idFabrica: '',
    motor: '',
    modelo: '',
    chasis: '',
    patente: '',
    preventa: '',
    centroCosto: '',
    duenio: '',
    entregarUsados_sinFacturar: 'S',
    chkEstado: true,
    chkConsignacion: false,
    chkCentroCosto: false,
    '@centro_costo': {
      type: 'java.lang.Integer',
      value: '-1',
    },
  };
  
  export const BodyUsed = {
    tabla_automotor: 'USD',
    estado: 'STKF',
    ultimos: '100',
    idFabrica: '',
    motor: '',
    modelo: '',
    chasis: '',
    patente: '',
    preventa: '',
    centroCosto: '',
    duenio: '',
    entregarUsados_sinFacturar: 'S',
    chkEstado: true,
    chkConsignacion: false,
    chkCentroCosto: false,
    consignacion: 'X',
    '@centro_costo': {
      type: 'java.lang.Integer',
      value: '-1',
    },
  };
  export const BodyNew = {
    tabla_automotor: 'USD',
    estado: 'arcb',
    ultimos: '100',
    idFabrica: '',
    motor: '',
    modelo: '',
    chasis: '',
    patente: '',
    preventa: '',
    centroCosto: '',
    duenio: '',
    entregarUsados_sinFacturar: 'S',
    chkEstado: true,
    chkConsignacion: false,
    chkCentroCosto: false,
    consignacion: 'X',
    '@centro_costo': {
      type: 'java.lang.Integer',
      value: '-1',
    },
  };
  
  export const registerBody = {
    apellido: '',
    barrio: '',
    cel: '',
    celLaboral: '',
    chkClienteTR: false,
    codPostal: '5000',
    comentario: '',
    cuit: '',
    depto: '',
    direccion: '',
    dni: '@FORM_DNI',
    dniConyugue: '',
    email: '@FORM_EMAIL',
    emailAlternativo: '@FORM_EMAIL',
    emailLaboral: '@FORM_EMAIL',
    estadoCivil: '',
    facturaMiPymes: false,
    fechaNac: '',
    fechaNacConyugue: '',
    inscripcionIG: '',
    localidad: '',
    moneda: 1,
    nacionalidad: '',
    nombreCompleto: '@FORM_NOMBRE_APELLIDO',
    nombreConyugue: '',
    nombres: '',
    numero: '',
    pais: 1,
    piso: '',
    provincia: '',
    sexo: '',
    telLaboral: '',
    telefono: '',
    tipoDocConyugue: '',
    tipoIngBruto: 8,
    tipoIva: 3,
    _cliente_id: '',
    _codigo: '',
    condicionVenta: '',
    tipoCliente: '',
    corredor: '',
    limite: 0,
    zona: '',
    descRepuestos: '',
    descServicios: '',
    cliente_id: '',
    _tipo: 'P',
    codigo: '@FORM_DNI',
    esPostventa: '',
  };
  export const bodyRemito = {
    fecha: '18/05/2024',
    comentarios: '',
    _codigo: '',
    _descripcion: '',
    _stock: '',
    _cantidad: 3,
    _precio: '',
    concepto: '-',
    corredor: '-',
    centroCosto: '-',
    condicion_venta: 'CONTADO',
    referencia: '',
    grupo: '-',
    zona: '-',
    recargo: 0,
    descuento: 0,
    exento: 0,
    gravado: '9660.00',
    impuestoInterno: '0.00',
    tasaIva: '21',
    tasaIva_id: 1,
    importeIva: '0.00',
    percepcionIva: '0.00',
    percepcionIB: '0.00',
    total: '11688.60',
    repuestosArr: [],
    repuestosDelArr: [],
    motivo: '',
    estado: 'PEN',
    dataLogin: {
      usuario: '',
    },
    '@sucursal': {
      type: 'java.lang.integer',
      value: '2',
    },
    '@puntoDeVenta': {
      type: 'java.lang.integer',
      value: '2',
    },
  };
  